version: "3.4"
services:
    ui-service:
        build:
            context: frontend
            dockerfile: Dockerfile
        networks:
            - services_network
        ports:
            - "5000:80"
        environment:
            - PORT=80
            - VITE_API_BASE_URL=http://localhost:5260
            - STATIC_FILES_DIR=./static

    backend:
        build:
            context: backend/GymBeam
            dockerfile: Dockerfile
        networks:
            - services_network
        ports:
            - "5260:80"

networks:
    services_network:
        external: true
